# Verbose reporting
REPORT_FREQUENCY = 20


# Default values
VALIDATION_SET_RELATIVE_SIZE = 0.2
TRAINING_SET_RELATIVE_SIZE = 0.6
TEST_SET_RELATIVE_SIZE = 0.2
REGULARIZATION_COEFFICIENT = 0.2
# +1 for the bias term
WEIGHT_LENGTH = 785

# Selecting 2 classes (digits) to make it binary
SELECTED_CLASSES = [0, 9]
LEARNING_RATE = 0.01
NUM_EPOCHS = 5

BCE_LOSS_STRING = "bce"
HINGE_LOSS_STRING = "hinge"